export { default as EmailController } from 'components/controllers/EmailController'
export { default as PasswordController } from 'components/controllers/PasswordController'
export { default as InitialRoute } from 'components/routes/InitialRoute'
export { default as PrivateRoute } from 'components/routes/PrivateRoute'
export { default as Loading } from 'components/Loading'
