export const mockConfig = {
  token: '123',
  theme: {
    brand: {
      50: '#F0EBFE',
      100: '#E2D8FD',
      200: '#C5B2FB',
      300: '#A88BF9',
      400: '#8B65F7',
      500: '#6F3FF5',
      600: '#5832C4',
      700: '#422593',
      800: '#2C1961',
    },
  },
  layout: {
    loginPage: {
      isSideImage: true,
      sideImageLink: 'url(https://source.unsplash.com/random)',
      alignmentToTheLeft: true,
      logoLink: 'url(https://picsum.photos/320/180)',
    },
    catalog: {
      iMenu: true,
    },
  },
  extraFunctionality: {
    news: false,
    settings: true,
  },
  i18n: {
    language: 'en',
    isRtl: false,
    translations: {
      loading: 'Loading...',
      logIn: 'Log In',
      loginDescription: 'Please fill your detail to access your account.',
      email: 'Email',
      emailAddress: 'Email Address',
      emailPlaceholder: 'Enter your email',
      emailValidation: 'Please enter a valid email address',
      password: 'Password',
      passwordPlaceholder: 'Enter password',
      passwordValidation: 'Please enter a password',
      rememberMe: 'Remember me',
      forgotPassword: 'Forgot Password',
      dontHaveAccount: 'Don’t have an account?',
      signUp: 'Sign Up',
      companyInfo: '© COMPANY INFO',
    },
    // translations: {
    //   "loading": "АЫВА...",
    //   "logIn": "ываыва",
    //   "loginDescription": "ывавы выа выа ы.",
    //   "email": "ыва",
    //   "emailAddress": "аппар ",
    //   "emailPlaceholder": "парап апр апрпар",
    //   "password": "арпар",
    //   "passwordPlaceholder": "апра апрп",
    //   "rememberMe": "апрапра рп",
    //   "forgotPassword": "авпвап апвапвап?",
    //   "dontHaveAccount": "ываыва ываыва а аываыва?",
    //   "signUp": "ываыва ыва ыв ",
    //   "companyInfo": "© ываываы",
    // },
  },
}
